### ISSUE TITLE
probable issue in src/WebbinoCore/WebServer.cpp

### ISSUE THREAD

**Issue by samuelestrozzieri** [SukkoPera/Webbino#17]
I was studying hard this powerful Arduino web application to know what it is capable of, when i saw something weird at WebServer.cpp line 294. I think that in if statement is missing an “)” wrapping the condition.

`					if (replyIsSuccessful (responseCode) {
						client.print (F(CONT_TYPE_HEADER));
						client.print (PSTR_TO_F (contType.getType ()));
						client.print (F(HEADER_END));
						
						if(ALLOW_CROSS_ORIGIN){
							client.print (F(ACCESS_CONTROL_ALLOW_ORIGIN));
							client.print (F(HEADER_END));
						}
						
						client.print (F(HEADER_END));

						sendContent (client, content, contType);
					}`

I haven’t execute neither used the code yet, I want to know its capability for my project before, but I think this missing bracket could be a problem. Am I missing something? 

I leave here the reference to the file: https://github.com/SukkoPera/Webbino/blob/11567ca5afaabbe2bf08f84ade2459a4eb066cb9/src/WebbinoCore/WebServer.cpp#L294

**Comment by qniens** [comment]
It compiles because replayIsSuccessful is a macro defined on line 76 as:
`#define replyIsSuccessful(x) ((x) / 100) == 2)`
Note the extra closing parenthesis. 
I'm not sure it this is intentional or a typo

**Comment by SukkoPera** [comment]
This is a typo, good catch! It shall be fixed.
