### ISSUE TITLE
HTTPRequestParser not work on sd card

### ISSUE THREAD

**Issue by ghost** [SukkoPera/Webbino#4]
I'm trying to run the library on a STM32 bluepill with an sd card, the web loads but does not resolve the http requests

what is not done is how to call the ledToggle function as it did with the flash configuration

any ideas? Thank you

**Comment by SukkoPera** [comment]
What version are you using? Also, I can't understand what the exact problem is, can you please enable debugging and provide the serial log?

**Comment by SukkoPera** [comment]
Closing because of lack of feedback and unable to reproduce.
