### ISSUE TITLE
Slower SD's and shared SPI's

### ISSUE THREAD

**Issue by vangalvin** [SukkoPera/Webbino#8]
I have a slightly slower card and the line is shared with a LoRo wifi radio so the SPI buss will only run at half speed. 

The fixt for this was prety simple. 
Change the line at about Line 87 to the following. this reduces the speed.
if (!SD.begin (pin, SD_SCK_MHZ(25))){

**Comment by SukkoPera** [comment]
I guess this refers to file `WebbinoCore/SdStorage.h`.

Anyway it's something peculiar to your setup, of course it cannot be generalized to everyone. Hence I'm leaving this for reference but I'm closing the issue.
